import type { Metadata } from "next";
import { Fragment_Mono, Familjen_Grotesk } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/Toaster";
import { MenuProvider } from "@/contexts/menuContext";
import MenuOverlay from "@/components/menu/MenuOverlay";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/lib/auth";
import GSAPInitialiser from "@/lib/gsapInitialiser";

const familjenGrotesk = Familjen_Grotesk({
  variable: "--font-familjen-grotesk",
  subsets: ["latin"],
});

const fragmentMono = Fragment_Mono({
  variable: "--font-fragment-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${familjenGrotesk.variable} ${fragmentMono.variable} tracking-[-0.03em] antialiased`}
      >
        <SessionProvider session={session}>
          <MenuProvider>
            <GSAPInitialiser />
            <main className="flex min-h-screen flex-col">{children}</main>
            <Toaster />

            <MenuOverlay />
          </MenuProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
