import type { Metadata } from "next";
import { Fragment_Mono, DM_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/Toaster";
import NextAuthProvider from "@/components/providers/SessionProvider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const fragmentMono = Fragment_Mono({
  variable: "--font-fragment-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${fragmentMono.variable} tracking-[-0.03em] antialiased`}
      >
        <NextAuthProvider>
          <main className="flex flex-col">{children}</main>
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
